plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace "MKLAUNCHER"
    compileSdk 35

    defaultConfig {
        applicationId "droid.mklauncher.app"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
        
        // 🟢 Mantém apenas o Português (Brasil) para descartar centenas de XMLs de idiomas das libs
        resourceConfigurations += ["pt-rBR"]
        multiDexEnabled false
    }

    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
            crunchPngs false
        }
        release {
            minifyEnabled true
            shrinkResources true // O R8 já remove recursos não utilizados da pasta res automaticamente
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    
    packaging {
        resources {
            excludes += [
                // 1. Metadados e artefatos do Kotlin/Coroutines
                'kotlin/**',
                '**/*.kotlin_builtins',
                '**/*.bin',
                'DebugProbesKt.bin',
                'META-INF/kotlinx-coroutines-core.version',
                'META-INF/kotlinx-coroutines-android.version',
                'META-INF/*.kotlin_module',
                'META-INF/*.version',

                // 2. Licenças e termos de bibliotecas
                'META-INF/LICENSE*',
                'META-INF/license*',
                'META-INF/NOTICE*',
                'META-INF/notice*',
                'META-INF/DEPENDENCIES*',
                'META-INF/dependencies*',
                'META-INF/AL2.0',
                'META-INF/LGPL2.1',

                // 3. Ferramentas e dados de layout/UI das libs
                'META-INF/com.android.tools/**',
                'META-INF/androidx.**',
                'META-INF/google/**',
                
                // 4. Assinaturas e arquivos de manifesto residual
                'META-INF/*.SF',
                'META-INF/*.DSA',
                'META-INF/*.RSA'
            ]
        }
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.material
}
